const ADD_ORGANISATION = 'ADD_ORGANISATION';
const EDIT_ORGANISATION = 'EDIT_ORGANISATION';
const DEL_ORGANISATION = 'DEL_ORGANISATION';

const ADD_USER = 'ADD_USER';
const EDIT_USER= 'EDIT_USER';
const DEL_USER = 'DEL_USER';
export {
    ADD_ORGANISATION,
    EDIT_ORGANISATION,
    DEL_ORGANISATION,
    ADD_USER,
    EDIT_USER,
    DEL_USER
}