const ADD_ORGANISATION = 'ADD_ORGANISATION';
const SHOW_ORGANISATION = 'SHOW_ORGANISATION';
const EDIT_ORGANISATION = 'EDIT_ORGANISATION';
const DEL_ORGANISATION = 'DEL_ORGANISATION';

const SHOW_LOGGED_USER = 'SHOW_LOGGED_USER';
const EDIT_USER= 'EDIT_USER';
const DEL_USER = 'DEL_USER';

const ADD_COLLECTION = "ADD_COLLECTION";
export {
    ADD_ORGANISATION,
    SHOW_ORGANISATION,
    EDIT_ORGANISATION,
    DEL_ORGANISATION,
    SHOW_LOGGED_USER,
    EDIT_USER,
    DEL_USER,
    ADD_COLLECTION
}